version: "3.0"
services:
  jenkins:
    image: labjenkinsgoogle
    ports:
      - 8080:8080
      - 50000:50000
    restart: unless-stopped
  nexus:
    image: sonatype/nexus3
    restart: always
    volumes:
      - "nexus-data:/sonatype-work"
    ports:
      - "8081:8081"
      - "8085:8085"
volumes:
  nexus-data: {}
